export enum AppErrorCode {
  ERR_UNKNOWN = 'ERR_UNKNOWN',
  ERR_LOAD_CONFIG = 'ERR_LOAD_CONFIG',
}

export enum UserErrorCode {
  ERR_DUPLICATE_USERNAME = 'ERR_DUPLICATE_USERNAME',
  ERR_DUPLICATE_EMAIL = 'ERR_DUPLICATE_EMAIL',
  ERR_USERNAME_NOT_FOUND = 'ERR_USERNAME_NOT_FOUND',
  ERR_WRONG_PASSWORD = 'ERR_WRONG_PASSWORD',
}
