#define(projectScope,string,project scope?)
#define(host,host-ip,host ip?)
#define(exposeHost,host-ip,port expose ip?)
#define(portRangeMin,number,min avaliable port?)
#define(portRangeMax,number,max avaliable port?)
#define(databaseType,select:[mysql|mariadb],database type?)
#define(databaseHost,string,database host?)
#define(databasePort,number,database port?)
#define(databaseUsername,string,database username?)
#define(databasePassword,password,database password?)
#define(databaseDB,string,database db name?)
#define(etcdHost,string,etcd host?)
#define(redisUrl,string,redis url?)
#define(redisDB,number,redis db?)
#define(aliKeyId,string,alicloud sdk access key id?)
#define(aliKeySecret,password,alicloud sdk access key secret?)
#define(aliPopAccountName,string,alicloud pop account name?)
#define(targetEtcdHost,string,target cluster etcd host?)
#define(targetScope,string,target cluster scope?)
#define(alias,string,alias name?)

debug: true
discovery:
  etcdComponentName: 'etcd'
  scope: $(projectScope)

logger:
  file:
    fileFormat: '[./logs/server-]YYYY-MM-DD[.log]'

node:
  alias: $(alias)
  api:
    portRange:
      - $(portRangeMin)
      - $(portRangeMax)
    host: 0.0.0.0
    exposeHost: $(exposeHost)

services:
  http-gateway:
    websocketListener:
      portRange:
        - $(portRangeMin)
        - $(portRangeMax)
      host: 0.0.0.0
      exposeHost: $(exposeHost)
      entryPath: '/ws'
    serverListener:
      portRange:
        - $(portRangeMin)
        - $(portRangeMax)
      host: $(host)
    traefik:
      prefix: traefik

  restful:
    tcpListener:
      portRange:
        - $(portRangeMin)
        - $(portRangeMax)
      host: $(host)

  auth:
    tcpListener:
      portRange:
        - $(portRangeMin)
        - $(portRangeMax)
      host: $(host)

  monitor:
    tcpListener:
      portRange:
        - $(portRangeMin)
        - $(portRangeMax)
      host: $(host)
    targetScopes:
      - $(targetScope)

  config:
    httpListener:
      port: 9010
      host: 0.0.0.0
      exposeHost: $(exposeHost)

components:
  business-redis:
    url: $(redisUrl)
    database: $(redisDB)
  business-database:
    database:
      type: $(databaseType)
      host: $(databaseHost)
      port: $(databasePort)
      username*: $(databaseUsername)
      password*: $(databasePassword)
      database: $(databaseDB)
  etcd:
    etcd:
      hosts:
      - $(etcdHost)
    ttl: 10
    prefix: $(projectScope)
  target-etcd:
    etcd:
      hosts:
      - $(targetEtcdHost)
    ttl: 10
    prefix: $(targetScope)
  ali-cloud:
    accessKeyId*: $(aliKeyId)
    accessKeySecret*: $(aliKeySecret)
    pop:
      accountName: $(aliPopAccountName)

workers:
  monitor:
    targets:
    - etcd:
        etcd:
          hosts:
          - $(targetEtcdHost)
        ttl: 10
        prefix: $(targetScope)
      scope: $(targetScope)
